spring:
  messages:
    basename: i18n.login
  datasource:
#   数据源基本配置
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/run_errands?characterEncoding=UTF-8&serverTimezone=GMT%2B8
  mail:
    host: smtp.qq.com
    username: 794758167@qq.com
    password: iyusvvjtsbdnbbhg
    default-encoding: utf-8
  redis:
    host: localhost
    port: 6379
    password: 
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0
#    lettuce:
#      shutdown-timeout: 300ms
        
      
server:
  port: 8080 
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
mail:
    fromMail:
      addr: 794758167@qq.com

#logging:
#  level:
#    web: debug